// <auto-generated />
using System;
using BackEnd_Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd_Persistence.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20230707180726_7")]
    partial class _7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Blog.BlogContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BlogGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("BlogGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BlogGroupId");

                    b.ToTable("BlogContents");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BlogGroupId = 2L,
                            BlogGroupName = "دانشگاه های قبرس",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 109, DateTimeKind.Local).AddTicks(5316),
                            ImageName = "EMU.jpg",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Tags = "دانشگاه,قبرس",
                            Text = "بعنوان قدیمی ترین و اولین دانشگاه دولتی در قبرس شمالی، تمامی دانشکده ها و رشته های دانشگاه مدیترانه شرقی از زمان تاسیس خود در سال 1979 مورد تایید شورای عالی آموزش عالی قبرس شمالی (YODAK) و همچنین آموزش عالی کشور ترکیه (YOK) می باشند.\r\n\r\nدانشگاه مدیترانه شرقی با بهره گیری از محوطه دانشگاهی بوسعت 110 هکتار و زیرساختی با بالاترین استاندارد اروپا مفتخر به ذکر واقعیات زیر می باشد:\r\nبزرگترین محوطه دانشگاهی در منطقه\r\n12 دانشکده و 204 رشته در تمامی مقاطع\r\nمدرسه آمادگی زبان های خارجی\r\nبیش از 1100 عضو هیات علمی از 35 کشور متفاوت\r\nمعتبرترین و بزرگترین دانشگاه انگلیسی زبان در قبرس شمالی\r\nآموزش بیش از 17500 دانشجو از 110 کشور\r\nامکان یادگیری حداقل یک زبان خارجی بغیر از زبان انگلیسی برای تمامی دانشجویان\r\nبهره مندی از بهترین و مدرنترین امکانات ورزشی و فرهنگی\r\nامکان استفاده از برنامه های متنوع تبادل دانشجو با بیش از 220 دانشگاه معتبر در سرتاسر جهان برای تمامی دانشجویان\r\nارایه مدارک فارغ التحصیلی معتبر در سرتاسر دنیا\r\nارایه مدارک مورد تایید معتبرترین نهادهای اعتبارسنجی دنیا\r\nجزو دانشگاه های برتر دنیا از نظر رتبه بندی دانشگاهی تایمز (Times Higher Education)\r\nکسب 5 ستاره QS از نظر کیفیت آموزش\r\nدانشگاه مدیترانه شرقی  از طریق آموزش مهارتهای نوآوری و تشویق به خلاقیت آینده حرفه ای دانشجویان خود را در سطح بین الملل تضمین می کند.\r\n\r\n\r\nدانشگاه مدیترانه شرقی استاندارد کیفیت آموزش را در 12 دانشکده، 108 رشته کارشناسی و 96 رشته در سطوح کارشناسی ارشد و دکتری خود تعریف نموده است.",
                            Title = "دانشگاه مدیترانه شرقی",
                            ViewCount = 0L
                        },
                        new
                        {
                            Id = 2L,
                            BlogGroupId = 2L,
                            BlogGroupName = "دانشگاه های قبرس",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 109, DateTimeKind.Local).AddTicks(8060),
                            ImageName = "EMU.jpg",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Tags = "دانشگاه,قبرس",
                            Text = "شما هم می توانید براحتی و بصورت آنلاین فرم درخواست اخذ پذیرش جهت پیوستن به خانواده بزرگ دانشگاه مدیترانه شرقی تکمیل و ارایه نمایید. برای تکمیل فرم درخواست اخذ پذیرش تنها کافی است با وارد کردن آدرس ایمیل خود در یکی از لینکهای زیر ثبت نام نمایید. دستور العمل ثبت نام و تکمیل فرم بصورت مشروح در فیلم آموزشی ذکر شده است: \r\nرشته های مقاطع کاردانی و کارشناسی\r\nرشته های مقاطع کارشناسی ارشد و دکتری\r\nنکات مهم:\r\nدانشگاه مدیترانه شرقی در ترمهای پاییز و بهار پذیرای دانشجویان جدید می باشد.\r\nهیچ گونه امتحان ورودی برای هیچ یک از رشته ها جهت اخذ پذیرش وجود ندارد.\r\nاخذ پذیرش از دانشگاه مدیترانه شرقی برای تمامی رشته ها و مقاطع کاملا رایگان می باشد. به هیچ عنوان هیچگونه وجهی جهت اخذ پذیرش به هیچ شخصی پرداخت ننمایید.\r\nشما می توانید به راحتی از بورسیه %50 درصد برای تمامی رشته های مقطع کارشناسی و کارشناسی ارشد باستثنا رشته های پزشکی و داروسازی بهره مند شوید. ",
                            Title = "مدارک لازم جهت ثبت نام در دانشگاه های قبرس",
                            ViewCount = 0L
                        },
                        new
                        {
                            Id = 3L,
                            BlogGroupId = 1L,
                            BlogGroupName = "اخبار قبرس",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 109, DateTimeKind.Local).AddTicks(8075),
                            ImageName = "CYP.jpg",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Tags = "شرایط جدید اقامت در قبرس",
                            Text = "خذ تابعیت با تولد فرزند در دنیا از دو قانون اصل خاک و اصل خون تبعیت میکند. برای مهاجرت از طریق تولد فرزند باید با قوانین آن کشور آشنا باشید. بسیار مهم است که بدانید آن کشور از کدام یک از این قوانین تبعیت میکند.\r\n\r\nقانون اصل خاک : در این قانون به دنیا آمدن و تولد فرزند در خاک کشور مورد نظر می باشد. بدون در نظر گرفتن اینکه پدر و مادر تابعیت کدام کشور را دارند.\r\n\r\nقانون اصل خون: در این اصل بسیار مهم آن است که یکی از پدر یا مادر یا هر دو، تبعه کشور مورد نظر باشند. در این حالت اینکه فرزند در کدام کشور متولد می شود اهمیتی ندارد.\r\n\r\nندا عباسیآنلاین",
                            Title = "شرایط جدید اخذ اقامت قبرس شمالی",
                            ViewCount = 0L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Blog.BlogGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 110, DateTimeKind.Local).AddTicks(4634),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "اخبار قبرس"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 110, DateTimeKind.Local).AddTicks(5342),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "دانشگاه های قبرس"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 110, DateTimeKind.Local).AddTicks(5356),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "کنسرت ها"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.AboutUs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AboutUs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 103, DateTimeKind.Local).AddTicks(681),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "املاک شبکه نقره ای با بیش از 6 سال سابقه درخشان آماده ی ارائه بهترین خدمات در راستای خرید ملک،سرمایه گذاری، اخذ اقامت، ثبت شرکت ، پذیرش دانشجویی و کلیه خدمات به همراه ارایه گشت های محلی با بکار گیری راهنمایان فارسی زبان بصورت گروهی و اختصاصی برای افراد و آژانسهای مسافرتی، به شما عزیزان در قبرس شمالی میباشد."
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkHour")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CellPhone = "+98-9123071411",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 108, DateTimeKind.Local).AddTicks(5569),
                            Email = "mahancomputer49@gmail.com",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "کیش - شهرک صدف - خیابان سبلان - پلاک 27 - واحد6",
                            Telephone = "00987644446503",
                            WorkHour = "شنبه تا جمعه ساعت 8-20"
                        },
                        new
                        {
                            Id = 2L,
                            CellPhone = "+90-5338355243",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 108, DateTimeKind.Local).AddTicks(5654),
                            Email = "mahancomputer49@gmail.com",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "قبرس شمالی - شهرک رویال سان - پرل 105",
                            Telephone = "00987644446503",
                            WorkHour = "شنبه تا جمعه ساعت 8-20"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.Banner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.CommonQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommonQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Answer = "قبرس با داشتن آب و هوای معتدل و مرطوب مدیترانه ایی مقصد مورد علاقه جهانگردان برای تعطیلات می باشد، با داشتن بیش از ۳۰۰ روز آفتابی و گرمایی مطلوب و کوهستان هایی در دل خود، از اعتدالی مدیترانه ایی برخوردار است.",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(8734),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Question = "قبرس کجاست؟"
                        },
                        new
                        {
                            Id = 2L,
                            Answer = "قبرس شمالی با داشتن ۳۶ درصد از مساحت کل جزیره قبرس به علت داشتن شرایط مهاجرتی آسان و مالیات بسیار کم در قیاس با جمهوری قبرس و سایر کشورهای اروپایی مورد توجه سرمایه گذارانی از نقاط مختلف دنیا قرار گرفته است",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 112, DateTimeKind.Local).AddTicks(395),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Question = "چرا قبرس شمالی؟"
                        },
                        new
                        {
                            Id = 3L,
                            Answer = "لیر ترکیه به عنوان ارز رایج این کشور شناخته می شود ولی خرید فروش ملک به پوند انگلستان می باشد و دلار و یورو هم در کنار این دو واحد پولی مورد استفاده قرار می گیرد.",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 112, DateTimeKind.Local).AddTicks(408),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Question = "واحد پولی قبرس شمالی چه می باشد؟"
                        },
                        new
                        {
                            Id = 4L,
                            Answer = "امنیت بالای قبرس شمالی در کنار رفاه مردم این کشور می تواند برای هر خانواده ایی دلیلی مناسب برای مهاجرت به قبرس شمالی باشد، بی علت نیست اگر قبرس شمالی در فهرست پنج کشور امن دنیا قرار گرفته است.",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 112, DateTimeKind.Local).AddTicks(412),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Question = "آیا قبرس شمالی برای زندگی خانوادگی مناسب می باشد؟"
                        },
                        new
                        {
                            Id = 5L,
                            Answer = "برای ورود به قبرس شمالی به صورت توریستی نیازی به اخذ ویزا نخواهید داشت.  برای داشتن اقامت بیشتر، از طریق اقامت دانشجویی، خرید ملک و یا ثبت شرکت و یا اشتغال میسر خواهد بود.",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 112, DateTimeKind.Local).AddTicks(415),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Question = "شرایط اخذ ویزا برای ورود به قبرس شمالی چگونه می باشد؟"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.ConstructorInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConstructorLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConstructorInformation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConstructorLogo = "Noyanlar.jpg",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 112, DateTimeKind.Local).AddTicks(9560),
                            Description = "گروه شرکت های نویانلار که در سال 1973 تأسیس شد، خدمات با کیفیت بالا را در تمام زمینه های صنعت ساخت و ساز در قبرس شمالی ارائه می دهد. این یک شرکت خانوادگی موفق است که کیفیت و رشد قابل اعتماد را در صنعت ساخت و ساز فراهم می کند. پروژه های ما مطابق با طرح های ساختمانی معاصر انجام می شود تا رضایتمندی بالا را فراهم کند.این مسیر باتاسیس شرکت معماری و مهندسی با مسئولیت محدود Arken توسط معمار کهنه کار گوکان نویان آغاز شد که در دهه های 1970 و 1980 بسیاری از پروژه های معماری را امضا کرد. در سال ۱۹۸۶ یک مهندس عمران با تجربه به نام Mustafa Noyan به این تیم پیوست.",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Noyanlar Group Constructor"
                        },
                        new
                        {
                            Id = 2L,
                            ConstructorLogo = "Ceaser.jpg",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 112, DateTimeKind.Local).AddTicks(9579),
                            Description = "اگر که به دنبال خرید ملک در قبرس شمالی بوده اید، بدون شک نام سزار ریزورت‌ به گوشتان خورده است. افیک گروپ، شرکت مادر مجتمع سزار قبرس، در سال های اخیر در قبرس ترک مشهور و به دنبال آن اولین پروژه ی این شرکت به نام سزار ریزورت بر سر زبان ها افتاد. شهرک سزار قبرس شمالی با وجود قیمت نسبتا بالا خود در مقایسه با املاک منطقه توانسته در دل فارسی زبانان جا باز کند و جمع کثیری از ایرانیان را در این شهرک گرد هم آورد.\r\nشنا در استخرهای تابستانه، نوشیدن لاته گرم در کافه پاریس در فصل پاییز، پایکوبی در مهمانی های پر زرق و برق زمستانه و در نهایت پیاده روی های سرخوشانه به مقصد ساحل لانگ بیچ در فصل بهار همگی از زیبایی های شهرک سزار قبرس شمالی هستند.\r\nآنچه مجتمع سزار قبرس را از دیگر شهرک های جزیره جدا میکند، شرایط پرداخت اقساطی واحدها می باشد.\r\nوقتی پای اقساط به میان می آید، توجه به تبصره های قرارداد از مسائل حساس و چالش برانگیز می شود. قرارداد مجتمع سزار قبرس حاوی شش تا هشت صفحه با بند ها و تبصره های مختلف به زبان انگلیسی است که عدم توجه و غفلت از هر یک از این بندها ممکن است ضرر و زیان جبران ناپذیری برای خریداران به همراه داشته باشد. امکان تغییر در جزییات تبصره ها با صحبت و رایزنی مشاور املاک شما با مدیران فروش سزار ریزورت وجود دارد. بنابراین پیش از امضای هرگونه قرارداد ملک شهرک سزار قبرس شمالی حتما با مشاور املاک مسلط به زبان انگلیسی و ترکی، مشورت کرده و راهنمایی های لازم را دریافت کنید تا در آینده با مشکلات مالی و حقوقی مواجه نشوید.",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ceaser Group"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.Logo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 119, DateTimeKind.Local).AddTicks(1087),
                            Description = "The Best real estate in cyprus",
                            ImageName = "silver.jpg",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Silver Net Real Estate"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 119, DateTimeKind.Local).AddTicks(1135),
                            Description = "The Best real estate in cyprus",
                            ImageName = "silver-net.jpg",
                            IsDelete = false,
                            IsSelected = false,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Silver Net Real Estate"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.RealEstateServices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RealEstateServices");
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.Social", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Socials");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 121, DateTimeKind.Local).AddTicks(4306),
                            Icon = "fa fa-instagram",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "instagram.com",
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 121, DateTimeKind.Local).AddTicks(4326),
                            Icon = "fa fa-facebok",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Link = "facebook.com",
                            Name = "Facebook"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.SpectacularLocationImages", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SpectacularlocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpectacularlocationId");

                    b.ToTable("SpectacularLocationImages");
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.Spectacularlocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spectacularlocations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 121, DateTimeKind.Local).AddTicks(9441),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ghost City"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 121, DateTimeKind.Local).AddTicks(9453),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wall City"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 121, DateTimeKind.Local).AddTicks(9456),
                            IsDelete = false,
                            IsSelected = false,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Long Beach"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 121, DateTimeKind.Local).AddTicks(9459),
                            IsDelete = false,
                            IsSelected = false,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Casino"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.TeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telegram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CellPhone = "09123071411",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 122, DateTimeKind.Local).AddTicks(6786),
                            Email = "mahancomputer49@gmail.com",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberPicture = "faryad.jpg",
                            MemberPosition = "CEO",
                            Name = "Faryad"
                        },
                        new
                        {
                            Id = 2L,
                            CellPhone = "09352499091",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 122, DateTimeKind.Local).AddTicks(6799),
                            Email = "faryad.abolhassani@yahoo.com",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberPicture = "farzad.jpg",
                            MemberPosition = "CEO",
                            Name = "Farzad"
                        },
                        new
                        {
                            Id = 3L,
                            CellPhone = "09122895170",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 122, DateTimeKind.Local).AddTicks(6946),
                            Email = "Mojgan.Nazari@gmail.com",
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberPicture = "mojgan.jpg",
                            MemberPosition = "Sell Manager",
                            Name = "Mojgan"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityName = "Kish",
                            CountryId = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(1494),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(1508)
                        },
                        new
                        {
                            Id = 2L,
                            CityName = "Tehran",
                            CountryId = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(3103),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(3111)
                        },
                        new
                        {
                            Id = 3L,
                            CityName = "Iskele",
                            CountryId = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(3114),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(3116)
                        },
                        new
                        {
                            Id = 4L,
                            CityName = "Girne",
                            CountryId = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(3119),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 111, DateTimeKind.Local).AddTicks(3121)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryFlag = "",
                            CountryName = "Iran",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 113, DateTimeKind.Local).AddTicks(4559),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 113, DateTimeKind.Local).AddTicks(4568)
                        },
                        new
                        {
                            Id = 2L,
                            CountryFlag = "",
                            CountryName = "Cyprus",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 113, DateTimeKind.Local).AddTicks(5541),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 113, DateTimeKind.Local).AddTicks(5548)
                        },
                        new
                        {
                            Id = 3L,
                            CountryFlag = "",
                            CountryName = "USA",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 113, DateTimeKind.Local).AddTicks(5552),
                            IsDelete = false,
                            IsSelected = false,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 113, DateTimeKind.Local).AddTicks(5553)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentPhoneNmber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConnectionFee")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("FloorSpace")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KeyHandOverDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfBathroom")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedroom")
                        .HasColumnType("int");

                    b.Property<string>("OwnerPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long>("PropertyContractTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PropertyStatus")
                        .HasColumnType("bit");

                    b.Property<long>("PropertyTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("StampDutyFee")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VATFee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PropertyContractTypeId");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyContractType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PropertyContractTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContractType = "فروش",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(112),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(132)
                        },
                        new
                        {
                            Id = 2L,
                            ContractType = "اجاره",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(830),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(839)
                        },
                        new
                        {
                            Id = 3L,
                            ContractType = "پیش فروش",
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(843),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(846)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project.Facility", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyFacilities");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyGallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyGalleries");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyPlans");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(7744),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(7756),
                            Type = "آپارتمان"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(8302),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(8310),
                            Type = "ویلا"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(8313),
                            IsDelete = false,
                            IsSelected = true,
                            LastUpdateDate = new DateTime(2023, 7, 7, 21, 37, 25, 120, DateTimeKind.Local).AddTicks(8315),
                            Type = "زمین"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<string>("VideoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyVideos");
                });

            modelBuilder.Entity("Domain.Entities.Blog.BlogContent", b =>
                {
                    b.HasOne("Domain.Entities.Blog.BlogGroup", "blogGroup")
                        .WithMany("BlogContents")
                        .HasForeignKey("BlogGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("blogGroup");
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.SpectacularLocationImages", b =>
                {
                    b.HasOne("Domain.Entities.GeneralSiteInformation.Spectacularlocation", "Spectacularlocation")
                        .WithMany("spectacularLocationImages")
                        .HasForeignKey("SpectacularlocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Spectacularlocation");
                });

            modelBuilder.Entity("Domain.Entities.Project.City", b =>
                {
                    b.HasOne("Domain.Entities.Project.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Project.Property", b =>
                {
                    b.HasOne("Domain.Entities.Project.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Project.PropertyContractType", "PropertyContractType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyContractTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Project.PropertyType", "PropertyTypes")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("PropertyContractType");

                    b.Navigation("PropertyTypes");
                });

            modelBuilder.Entity("Domain.Entities.Project.Facility", b =>
                {
                    b.HasOne("Domain.Entities.Project.Property", "Property")
                        .WithMany("PropertyFacilities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyGallery", b =>
                {
                    b.HasOne("Domain.Entities.Project.Property", "ProPerty")
                        .WithMany("PropertyGalleries")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProPerty");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyPlan", b =>
                {
                    b.HasOne("Domain.Entities.Project.Property", "Property")
                        .WithMany("PropertyPlans")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyVideo", b =>
                {
                    b.HasOne("Domain.Entities.Project.Property", "ProPerty")
                        .WithMany("PropertyVideos")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProPerty");
                });

            modelBuilder.Entity("Domain.Entities.Blog.BlogGroup", b =>
                {
                    b.Navigation("BlogContents");
                });

            modelBuilder.Entity("Domain.Entities.GeneralSiteInformation.Spectacularlocation", b =>
                {
                    b.Navigation("spectacularLocationImages");
                });

            modelBuilder.Entity("Domain.Entities.Project.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Domain.Entities.Project.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Project.Property", b =>
                {
                    b.Navigation("PropertyFacilities");

                    b.Navigation("PropertyGalleries");

                    b.Navigation("PropertyPlans");

                    b.Navigation("PropertyVideos");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyContractType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Domain.Entities.Project.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
